### ISSUE TITLE
A Tutorial

### ISSUE THREAD

**Issue by MattW1PE** [ArchonKlaus/AdvancedScoreboard#3]
Could you make a tutorial on how to use I’m stuck at the part where you have to write the world name you want it to work in

**Comment by ZZWILLIAMXXTrue** [comment]
That part is kinda hard to understand... So here is an example of what I have...
worlds:
  world:
    title:
    - '{RANDOMCOLOR}UniPVP'
    lines:
    - '{RANDOMCOLOR}Kills: {KILLS}'
    - '{RANDOMCOLOR}Deaths: {DEATHS}'    
    - '{RANDOMCOLOR}KDR: {KDR}'
    - '{RANDOMCOLOR}Faction: {FACTION}'
    - '{RANDOMCOLOR}Faction Power: {FPOWER}'
    - '{RANDOMCOLOR}Money: {MONEY}'
  NormalWorld:
    title:
    - '{RANDOMCOLOR}UniPVP'
    lines:
    - '{RANDOMCOLOR}Kills: {KILLS}'
    - '{RANDOMCOLOR}Deaths: {DEATHS}'    
    - '{RANDOMCOLOR}KDR: {KDR}'
    - '{RANDOMCOLOR}Faction: {FACTION}'
    - '{RANDOMCOLOR}Faction Power: {FPOWER}'
    - '{RANDOMCOLOR}Money: {MONEY}'

**Comment by BroCrows** [comment]
Just copy the first one and paste it.
