### ISSUE TITLE
More Tags?

### ISSUE THREAD

**Issue by BroCrows** [ArchonKlaus/AdvancedScoreboard#5]
I have a lot if ideas for tags.
{bounty} - Shows the amount of bounty a player has.(Needs Bounty by Jaxkdev)
{worldborder} - Shows how far you are away from the worldborder.(Needs WorldBorder by ArceusMatt)
{votes} - Shows the amount of votes the player has.(Needs BetterVoting by TwistedAsylumMC or PocketVote by ProjectInfinity)
{gapplecooldown} - Shows the cooldown of a gapple.(Needs GappleCooldown by CaptainDuck)
{godapplecooldown} - Show the cooldown of a god apple.(Needs GappleCooldown by CaptainDuck)
Also can you add multiple text for the lines? Like shows the first part, then second part, then third part then redo?

**Comment by samupozzo** [comment]
Next version will have these new things (v1. 3)

**Comment by benda95280** [comment]
Any news ?

**Comment by BroCrows** [comment]
Not that I know of. Idk if he quit or not. I hope he didnt

**Comment by samupozzo** [comment]
Actually I'm working in other projects for some servers, I will try to find some free time to make new version of AdvancedScoreboard. I hope to get some time, there is a lot of work here!

**Comment by BroCrows** [comment]
Ok!

**Comment by SamuelPozzobon** [comment]
New tags coming soon

**Comment by samupozzo** [comment]
Hi, it's been a while since I created AdvancedScoreboard! At the moment, I'm updating the plugin to PM4, and adding more features in the next weeks/month. Expect updates in the repo!
